{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE LambdaCase #-}

-- |
-- Module      : LeadProfiler.Emit.TypeScript
-- Description : Emit TypeScript type definitions from the Haskell ADTs.
--
-- The original Next.js project has a @lib/lead-profiler-types.ts@ file
-- that defines the TypeScript types for the three routes' outputs. That
-- file is hand-maintained and can drift from the actual JSON the LLM
-- produces — different field name conventions, different enum values, etc.
--
-- This module generates TypeScript type definitions /directly/ from the
-- Haskell ADTs, so the schema is defined in one place (the Haskell
-- source). The output can be written to a @.ts@ file and imported by the
-- Next.js app.
module LeadProfiler.Emit.TypeScript
  ( emitTypeScript
  , tsLeadObservation
  , tsProspectAudit
  , tsUserServices
  ) where

import           LeadProfiler.Prelude
import           LeadProfiler.Schemas.LeadObservation  (CallToAction(..))
import           LeadProfiler.Schemas.ProspectAudit
import           LeadProfiler.Schemas.Common          (TriBool(..), Confidence(..))

import qualified Data.Text as T

-- | Generate the full TypeScript definitions file as 'Text'.
emitTypeScript :: Text
emitTypeScript = T.unlines
  [ "// ---------------------------------------------------------------------------"
  , "// Auto-generated by lead-profiler-haskell Emit.TypeScript."
  , "// Do not edit by hand — edit the Haskell ADTs and re-run the generator."
  , "//"
  , "// These types mirror the JSON the lead-profiler-haskell validators produce."
  , "// The Next.js app can import them directly to get type-safe access to the"
  , "// validated VLM/LLM output."
  , "// ---------------------------------------------------------------------------"
  , ""
  , tsLeadObservation
  , ""
  , tsProspectAudit
  , ""
  , tsUserServices
  ]

-- | Emit TypeScript types for the @analyze-lead-images@ route.
tsLeadObservation :: Text
tsLeadObservation = T.unlines
  [ "// === analyze-lead-images ==="
  , ""
  , "export type Confidence = \"high\" | \"medium\" | \"low\";"
  , "export type TriBool = \"yes\" | \"no\" | \"cannot_determine\";"
  , "export type CallToAction = \"dm\" | \"call\" | \"link\" | \"none\" | \"cannot_determine\";"
  , ""
  , "export interface ObservationNotes {"
  , "  pace: string;"
  , "  people_orientation: string;"
  , "  content_shape: string;"
  , "  engagement: string;"
  , "  self_presentation: string;"
  , "  pressure_tells: string;"
  , "}"
  , ""
  , "export interface DigitalPresenceAudit {"
  , "  has_website: TriBool;"
  , "  has_booking_or_payment_link: TriBool;"
  , "  has_google_reviews: TriBool;"
  , "  primary_call_to_action: CallToAction;"
  , "  bio_text: string;"
  , "  follower_count: string;"
  , "}"
  , ""
  , "export interface LeadObservation {"
  , "  extraction_confidence: Confidence;"
  , "  observation_notes: ObservationNotes;"
  , "  digital_presence_audit: DigitalPresenceAudit;"
  , "  screenshot_summary: string;"
  , "  what_i_could_not_determine: string[];"
  , "}"
  ]

-- | Emit TypeScript types for the @prospect-content-audit@ route.
tsProspectAudit :: Text
tsProspectAudit = T.unlines
  [ "// === prospect-content-audit ==="
  , ""
  , "export type PolishLevel = \"polished\" | \"semi-polished\" | \"raw\";"
  , "export type Consistency = \"consistent\" | \"inconsistent\";"
  , "export type PostingPattern = \"consistent\" | \"sporadic\" | \"campaign-based\";"
  , "export type CommentVolume = \"low\" | \"medium\" | \"high\" | \"cannot_determine\";"
  , "export type TriYesNo = \"yes\" | \"no\" | \"cannot_determine\";"
  , "export type PitchRecommendation = \"yes\" | \"no\" | \"maybe\";"
  , "export type DiscStyle ="
  , "  | \"D\" | \"i\" | \"S\" | \"C\""
  , "  | \"Di\" | \"iD\" | \"iS\" | \"Si\""
  , "  | \"SC\" | \"CS\" | \"DC\" | \"CD\""
  , "  | \"unknown\";"
  , ""
  , "export interface ContentTheme {"
  , "  theme: string;"
  , "  estimated_percentage: number;"
  , "  example_post: string;"
  , "}"
  , ""
  , "export interface VisualStyle {"
  , "  description: string;"
  , "  polish_level: PolishLevel;"
  , "  consistency: Consistency;"
  , "  colors_or_design_notes: string;"
  , "}"
  , ""
  , "export interface PostingStrategy {"
  , "  formats_used: string[];"
  , "  pattern: PostingPattern;"
  , "  recurring_series: string[];"
  , "}"
  , ""
  , "export interface EngagementPatterns {"
  , "  comment_volume: CommentVolume;"
  , "  reply_behavior: string;"
  , "  negative_comments_visible: TriYesNo;"
  , "  user_generated_content: TriYesNo;"
  , "}"
  , ""
  , "export interface BrandVoice {"
  , "  tone: string;"
  , "  language_register: string;"
  , "  signature_phrases: string[];"
  , "  audience_address: string;"
  , "}"
  , ""
  , "export interface GapsAndOpportunities {"
  , "  missing_content: string[];"
  , "  operational_pain_points: string[];"
  , "  digital_presence_gaps: string[];"
  , "  services_to_pitch: string[];"
  , "}"
  , ""
  , "export interface SalesRecommendation {"
  , "  should_pitch: PitchRecommendation;"
  , "  why: string;"
  , "  pitch_angle: string;"
  , "  likely_pain_point: string;"
  , "  rough_disc_style: DiscStyle;"
  , "  recommended_register: string;"
  , "}"
  , ""
  , "export interface ProspectAudit {"
  , "  audit_confidence: Confidence;"
  , "  content_themes: ContentTheme[];"
  , "  visual_style: VisualStyle;"
  , "  posting_strategy: PostingStrategy;"
  , "  engagement_patterns: EngagementPatterns;"
  , "  brand_voice: BrandVoice;"
  , "  gaps_and_opportunities: GapsAndOpportunities;"
  , "  sales_recommendation: SalesRecommendation;"
  , "  what_i_could_not_determine: string[];"
  , "}"
  ]

-- | Emit TypeScript types for the @read-portfolio@ route.
tsUserServices :: Text
tsUserServices = T.unlines
  [ "// === read-portfolio ==="
  , ""
  , "export interface UserServices {"
  , "  primary: string;"
  , "  secondary: string;"
  , "  past_work_examples: string[];"
  , "  track_record: string;"
  , "  service_depth: string;"
  , "  extraction_notes: string;"
  , "}"
  ]

-- | Internal helper kept for potential future use: format a list of
-- string-literal alternatives for a TypeScript string-union type.
_tsStringUnion :: [Text] -> Text
_tsStringUnion xs = T.intercalate " | " (map (\t -> "\"" <> t <> "\"") xs)
