{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE LambdaCase #-}

module LeadProfiler.EmitSpec (spec) where

import           Test.Hspec
import           Test.Hspec.Expectations

import           LeadProfiler.Prelude
import           LeadProfiler.Emit
import           LeadProfiler.Emit.TypeScript
import           LeadProfiler.Emit.JsonSchema
import           LeadProfiler.Emit.Fixtures

import qualified Data.Aeson          as A
import qualified Data.Aeson.KeyMap   as KM
import qualified Data.Text           as T

spec :: Spec
spec = do
  describe "emitTypeScript" $ do
    it "contains all three route type declarations" $ do
      emitTypeScript `shouldSatisfy` (T.isInfixOf "LeadObservation")
      emitTypeScript `shouldSatisfy` (T.isInfixOf "ProspectAudit")
      emitTypeScript `shouldSatisfy` (T.isInfixOf "UserServices")

    it "declares the Confidence type" $
      emitTypeScript `shouldSatisfy` (T.isInfixOf "type Confidence")

    it "declares the DiscStyle union" $
      emitTypeScript `shouldSatisfy` (T.isInfixOf "type DiscStyle")

    it "includes the auto-generated header comment" $
      emitTypeScript `shouldSatisfy` (T.isInfixOf "Auto-generated by lead-profiler-haskell")

  describe "emitJsonSchemas" $ do
    it "contains all three named schemas" $ do
      let v = emitJsonSchemas
      v `shouldSatisfy` hasKey "lead_observation"
      v `shouldSatisfy` hasKey "prospect_audit"
      v `shouldSatisfy` hasKey "user_services"

    it "each schema has a $schema, title, type, properties, required" $ do
      let v = emitJsonSchemas
          checkRoute :: Text -> IO ()
          checkRoute key =
            case lookupKey v key of
              Nothing -> expectationFailure ("missing route: " <> T.unpack key)
              Just schema -> do
                schema `shouldSatisfy` hasKey "$schema"
                schema `shouldSatisfy` hasKey "title"
                schema `shouldSatisfy` hasKey "type"
                schema `shouldSatisfy` hasKey "properties"
                schema `shouldSatisfy` hasKey "required"
      checkRoute "lead_observation"
      checkRoute "prospect_audit"
      checkRoute "user_services"

  describe "emitAllFixtures" $ do
    it "contains all three fixtures" $ do
      let v = emitAllFixtures
      v `shouldSatisfy` hasKey "lead_observation"
      v `shouldSatisfy` hasKey "prospect_audit"
      v `shouldSatisfy` hasKey "user_services"

    it "the user-services fixture has non-empty primary" $ do
      case lookupKey emitAllFixtures "user_services" of
        Just us -> us `shouldSatisfy` hasKey "primary"
        Nothing -> expectationFailure "missing user_services fixture"

  describe "emitAll" $ do
    it "contains both json_schemas and fixtures" $ do
      emitAll `shouldSatisfy` hasKey "json_schemas"
      emitAll `shouldSatisfy` hasKey "fixtures"

-- | Helper: check whether a Value is an Object containing a given key.
hasKey :: Text -> Value -> Bool
hasKey k = \case
  Object o -> case lookupKey (Object o) k of
                Just _  -> True
                Nothing -> False
  _        -> False

-- | Helper: look up a key in a Value (if it's an Object).
lookupKey :: Value -> Text -> Maybe Value
lookupKey (Object o) k = lookupInKeyMap k o
lookupKey _ _ = Nothing

lookupInKeyMap :: Text -> Object -> Maybe Value
lookupInKeyMap k o = case KM.lookup (fromText k) o of
  Just v  -> Just v
  Nothing -> Nothing
